config/routes.rb
Rails.application.routes.draw do
  resources :buttons
  post "/webhook", to: "buttons#webhook"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/button.rb
class Button < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  before_action :set_button, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:webhook]

  def webhook
    msg = (["very good luck", "good luck", "bad luck", "very bad luck", "a little luck"])[rand 5]
    render json: { stores: {message: "#{msg}"}}
  end

  # GET /buttons
  # GET /buttons.json
  def index
    @buttons = Button.all
  end

  # GET /buttons/1
  # GET /buttons/1.json
  def show
  end

  # GET /buttons/new
  def new
    @button = Button.new
  end

  # GET /buttons/1/edit
  def edit
  end

  # POST /buttons
  # POST /buttons.json
  def create
    @button = Button.new(button_params)

    respond_to do |format|
      if @button.save
        format.html { redirect_to @button, notice: 'Button was successfully created.' }
        format.json { render :show, status: :created, location: @button }
      else
        format.html { render :new }
        format.json { render json: @button.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buttons/1
  # PATCH/PUT /buttons/1.json
  def update
    respond_to do |format|
      if @button.update(button_params)
        format.html { redirect_to @button, notice: 'Button was successfully updated.' }
        format.json { render :show, status: :ok, location: @button }
      else
        format.html { render :edit }
        format.json { render json: @button.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buttons/1
  # DELETE /buttons/1.json
  def destroy
    @button.destroy
    respond_to do |format|
      format.html { redirect_to buttons_url, notice: 'Button was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_button
      @button = Button.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def button_params
      params.require(:button).permit(:name, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/views/buttons/_form.html.erb
<%= form_for(button) do |f| %>
  <% if button.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(button.errors.count, "error") %> prohibited this button from being saved:</h2>

      <ul>
      <% button.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :count %>
    <%= f.number_field :count %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buttons/edit.html.erb
<h1>Editing Button</h1>

<%= render 'form', button: @button %>

<%= link_to 'Show', @button %> |
<%= link_to 'Back', buttons_path %>

app/views/buttons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buttons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buttons.each do |button| %>
      <tr>
        <td><%= button.name %></td>
        <td><%= button.count %></td>
        <td><%= link_to 'Show', button %></td>
        <td><%= link_to 'Edit', edit_button_path(button) %></td>
        <td><%= link_to 'Destroy', button, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Button', new_button_path %>

app/views/buttons/new.html.erb
<h1>New Button</h1>

<%= render 'form', button: @button %>

<%= link_to 'Back', buttons_path %>

app/views/buttons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @button.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @button.count %>
</p>

<%= link_to 'Edit', edit_button_path(@button) %> |
<%= link_to 'Back', buttons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mitoh247Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>